FROM node:18-alpine AS builder
WORKDIR /app
COPY frontend/package*.json ./
RUN npm install
COPY frontend/ .
RUN npm run build
FROM nginx:alpine
COPY devops/docker/nginx.conf /etc/nginx/conf.d/nginx.conf
COPY --from=builder /app/dist /usr/share/nginx/html
EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
# docker build -t frontend:latest -f devops/docker/Dockerfile.frontend .
# docker run -d -p 80:80 frontend:latest