apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      containers:
        - name: {{ .Values.app.name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          ports:
            - name: api
              containerPort: {{ .Values.containerPort }}
          env:
            - name: PORT
              value: "{{ .Values.env.PORT }}"
            - name: NODE_ENV
              value: "{{ .Values.env.NODE_ENV }}"
            - name: CLOUDINARY_NAME
              value: "{{ .Values.env.CLOUDINARY_NAME }}"
            - name: CLOUDINARY_API
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.envSecrets.CLOUDINARY_API.secretName }}
                  key: {{ .Values.envSecrets.CLOUDINARY_API.secretKey }}
            - name: CLOUDINARY_SECRET
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.CLOUDINARY_SECRET.secretName }}
                  key: {{ .Values.envSecrets.CLOUDINARY_SECRET.secretKey }}
            - name: MONGODB_URI
              value: "{{ .Values.env.MONGODB_URI }}"
            - name: MONGO_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.envSecrets.MONGO_PASSWORD.secretName }}
                  key: {{ .Values.envSecrets.MONGO_PASSWORD.secretKey }}
            - name: JWT_SECRET
              valueFrom: 
                secretKeyRef:
                  name: {{ .Values.envSecrets.JWT_SECRET.secretName }}
                  key: {{ .Values.envSecrets.JWT_SECRET.secretKey }}
      imagePullSecrets:
        - name: {{ .Values.imagePullSecrets }}
