apiVersion: v1
data:
  CLOUDINARY_API: ODI2NjM1Mzg0NjI3MjI1
kind: Secret
metadata:
  name: image-api
type: Opaque
---
apiVersion: v1
data:
  CLOUDINARY_SECRET: MjNBZHR1djRZeDdCa3ljcWJ1dnNCMTJNMjlN
kind: Secret
metadata:
  name: image-api-secret
type: Opaque
---
apiVersion: v1
data:
  JWT_SECRET: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBaQ0k2SWpFeU16UTFOaUlzSW5WelpYSnVZVzFsSWpvaWRHVnpkSFZ6WlhJaUxDSnBZWFFpT2pFM05ETTBNakF5TnpZc0ltVjRjQ0k2TVRjME16UXlNemczTm4wLlIwQmNGMDF4RVdOUFkydEJhTjFhU3ZCei0wc2N5MERKQktQM1VucHdNc1k=
kind: Secret
metadata:
  name: jwt-secret
  namespace: default
type: Opaque
---
apiVersion: v1
data:
  MONGO_PASSWORD: QWFnR3E3T1JmUmViclo3Vw==
kind: Secret
metadata:
  name: mongo-pass
  namespace: default
type: Opaque


