apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-http
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: agam.kushwaha234332@gmail.com
    privateKeySecretRef:
      name: letsencrypt-http-key
    solvers:
      - http01:
          ingress:
            class: nginx
