name: Deploy to Amazon EKS

on:
  push:
    branches:
      - feature

env:
  AWS_REGION: ap-south-1
  ECR_REPOSITORY: backendrepo
  IMAGE_TAG: ${{ github.sha }}

jobs:
  deploy:
    name: Deploy to Amazon EKS
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to Amazon ECR
        id: ecr-login
        uses: aws-actions/amazon-ecr-login@v1

      - name: Build, Tag and Push Docker image
        run: |
          docker build -t ${{ env.ECR_REPOSITORY }}:latest -f backend/Dockerfile .
          docker tag ${{ env.ECR_REPOSITORY }}:latest ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
          docker push ${{ steps.ecr-login.outputs.registry }}/${{ env.ECR_REPOSITORY }}:${{ env.IMAGE_TAG }}
